function state = mfc_siso_init(cfg)
%MFC_SISO_INIT Zero-initialize the state struct for MFC_SISO_STEP.
%
%   state = MFC_SISO_INIT(cfg)
%
%   Returns the all-zero controller state matching the configuration built
%   by MFC_SISO_CONFIG. The window buffers are sized from the precomputed
%   quadrature kernel for sliding-window variants and collapse to scalar
%   placeholders for algebraic variants.
%
%   State fields
%     .sp_filt_km1/2   reference trajectory filter history
%     .z_km1, .z_km2   algebraic estimator drive-signal history
%     .num_filt_km1/2  algebraic estimator smoothed numerator history
%     .den_filt_km1/2  algebraic estimator smoothed denominator history
%     .y_buf, .u_buf   sliding-window buffers [(n+1)x1], newest last
%     .err_km1         previous tracking error (derivative / integral)
%     .int_err         trapezoidal error integral
%     .u_km1           previously issued command (internal feedback path)
%
%   See also MFC_SISO_CONFIG, MFC_SISO_STEP.

if cfg.algebraic
    n_buf = 1;                             % unused placeholder
else
    n_buf = cfg.kernel.n_intervals + 1;
end

state = struct( ...
    'sp_filt_km1',  0, ...
    'sp_filt_km2',  0, ...
    'z_km1',        0, ...
    'z_km2',        0, ...
    'num_filt_km1', 0, ...
    'num_filt_km2', 0, ...
    'den_filt_km1', 0, ...
    'den_filt_km2', 0, ...
    'y_buf',        zeros(n_buf, 1), ...
    'u_buf',        zeros(n_buf, 1), ...
    'err_km1',      0, ...
    'int_err',      0, ...
    'u_km1',        0);
end
